### ISSUE TITLE
Setup not working in Ubuntu 16.10 and Ubuntu 17.04

### ISSUE THREAD

**Issue by rayitopy** [radek-senfeld/ffvideo#1]
I tried to make the installation in Ubuntu 16.10 and 17.04 but is not working.
Here is the pip3 install command output.

> pip3 install git+https://github.com/radek-senfeld/ffvideo.git#egg=ffvideo
Collecting ffvideo from git+https://github.com/radek-senfeld/ffvideo.git#egg=ffvideo
  Cloning https://github.com/radek-senfeld/ffvideo.git to /tmp/pip-build-vbdtelq8/ffvideo
Installing collected packages: ffvideo
  Running setup.py install for ffvideo ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vbdtelq8/ffvideo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-iss843mm-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_ext
    skipping 'ffvideo/ffvideo.c' Cython extension (up-to-date)
    building 'ffvideo' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/ffvideo
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-7CCmgg/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/ffmpeg -I/usr/include/python3.5m -c ffvideo/ffvideo.c -o build/temp.linux-x86_64-3.5/ffvideo/ffvideo.o
    ffvideo/ffvideo.c: In function ‘__pyx_pf_7ffvideo_11VideoStream_2__init__’:
    ffvideo/ffvideo.c:2815:5: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
         __pyx_t_1 = (((__pyx_v_self->format_ctx->streams[__pyx_v_i])->codec->codec_type == AVMEDIA_TYPE_VIDEO) != 0);
         ^~~~~~~~~
    In file included from ffvideo/ffvideo.c:252:0:
    /usr/include/x86_64-linux-gnu/libavformat/avformat.h:893:21: note: declared here
         AVCodecContext *codec;
                         ^~~~~
    ffvideo/ffvideo.c:2933:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
       __pyx_t_12 = __pyx_v_self->stream->codec;
       ^~~~~~~~~~
    In file included from ffvideo/ffvideo.c:252:0:
    /usr/include/x86_64-linux-gnu/libavformat/avformat.h:893:21: note: declared here
         AVCodecContext *codec;
                         ^~~~~
    ffvideo/ffvideo.c: In function ‘__pyx_pf_7ffvideo_11VideoStream_4__dealloc__’:
    ffvideo/ffvideo.c:3384:5: warning: ‘av_free_packet’ is deprecated [-Wdeprecated-declarations]
         av_free_packet((&__pyx_v_self->packet));
         ^~~~~~~~~~~~~~
    In file included from ffvideo/ffvideo.c:251:0:
    /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4473:6: note: declared here
     void av_free_packet(AVPacket *pkt);
          ^~~~~~~~~~~~~~
    ffvideo/ffvideo.c: In function ‘__pyx_pf_7ffvideo_11VideoStream_8__decode_next_frame’:
    ffvideo/ffvideo.c:3724:13: warning: ‘avcodec_decode_video2’ is deprecated [-Wdeprecated-declarations]
                 __pyx_v_ret = avcodec_decode_video2(__pyx_v_self->codec_ctx, __pyx_v_self->frame, (&__pyx_v_frame_finished), (&__pyx_v_self->packet));
                 ^~~~~~~~~~~
    In file included from ffvideo/ffvideo.c:251:0:
    /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4812:5: note: declared here
     int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
         ^~~~~~~~~~~~~~~~~~~~~
    ffvideo/ffvideo.c:3762:9: warning: ‘av_free_packet’ is deprecated [-Wdeprecated-declarations]
             av_free_packet((&__pyx_v_self->packet));
             ^~~~~~~~~~~~~~
    In file included from ffvideo/ffvideo.c:251:0:
    /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4473:6: note: declared here
     void av_free_packet(AVPacket *pkt);
          ^~~~~~~~~~~~~~
    ffvideo/ffvideo.c:3834:5: warning: ‘av_free_packet’ is deprecated [-Wdeprecated-declarations]
         av_free_packet((&__pyx_v_self->packet));
         ^~~~~~~~~~~~~~
    In file included from ffvideo/ffvideo.c:251:0:
    /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4473:6: note: declared here
     void av_free_packet(AVPacket *pkt);
          ^~~~~~~~~~~~~~
    ffvideo/ffvideo.c: In function ‘__pyx_pf_7ffvideo_11VideoStream_12current’:
    ffvideo/ffvideo.c:4152:3: warning: ‘avpicture_get_size’ is deprecated [-Wdeprecated-declarations]
       __pyx_v_buflen = avpicture_get_size(__pyx_v_self->ffmpeg_frame_mode, __pyx_v_self->frame_width, __pyx_v_self->frame_height);
       ^~~~~~~~~~~~~~
    In file included from ffvideo/ffvideo.c:251:0:
    /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:5468:5: note: declared here
     int avpicture_get_size(enum AVPixelFormat pix_fmt, int width, int height);
         ^~~~~~~~~~~~~~~~~~
    ffvideo/ffvideo.c:4209:9: warning: ‘avpicture_fill’ is deprecated [-Wdeprecated-declarations]
             avpicture_fill(((struct AVPicture *)__pyx_v_scaled_frame), ((__pyx_t_6ffmpeg_uint8_t *)(&(*((char *) ( /* dim=0 */ (__pyx_v_data_view.data + __pyx_t_5 * __pyx_v_data_view.strides[0]) ))))), __pyx_v_self->ffmpeg_frame_mode, __pyx_v_self->frame_width, __pyx_v_self->frame_height);
             ^~~~~~~~~~~~~~
    In file included from ffvideo/ffvideo.c:251:0:
    /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:5453:5: note: declared here
     int avpicture_fill(AVPicture *picture, const uint8_t *ptr,
         ^~~~~~~~~~~~~~
    ffvideo/ffvideo.c: In function ‘PyInit_ffvideo’:
    ffvideo/ffvideo.c:19389:30: error: ‘PIX_FMT_RGB24’ undeclared (first use in this function)
       __pyx_t_2 = PyInt_FromLong(PIX_FMT_RGB24); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                  ^~~~~~~~~~~~~
    ffvideo/ffvideo.c:19389:30: note: each undeclared identifier is reported only once for each function it appears in
    ffvideo/ffvideo.c:19401:30: error: ‘PIX_FMT_GRAY8’ undeclared (first use in this function)
       __pyx_t_2 = PyInt_FromLong(PIX_FMT_GRAY8); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                  ^~~~~~~~~~~~~
    ffvideo/ffvideo.c:19413:30: error: ‘PIX_FMT_YUV420P’ undeclared (first use in this function)
       __pyx_t_2 = PyInt_FromLong(PIX_FMT_YUV420P); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                  ^~~~~~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vbdtelq8/ffvideo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-iss843mm-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-vbdtelq8/ffvideo/

**Comment by radek-senfeld** [comment]
Hi, this fork is obsolete. We've switched to PyAV - https://github.com/mikeboers/PyAV

**Comment by rayitopy** [comment]
Ok, thanks.
